name: SARIF annotator
description: Parse SARIF files and output annotations
author: Equisoft
branding:
  color: orange
  icon: check-square

inputs:
  level:
    description: Include issues with this level or higher.
    required: true
    default: error
  limit:
    description: Limit how many annotations are created.
    required: true
    default: "50"
  sarif-path:
    description: The path to the SARIF file to parse.
    required: true
  title:
    description: Optional title for these annotations.
    required: false

runs:
  using: node16
  main: dist/index.js
