name: Validate

on:
  pull_request: { }
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2
      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2
      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1
      - name: Run ESLint
        uses: equisoft-actions/yarn-eslint@v2
        with:
          enable-annotations: false

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2
      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1
      - name: Run Jest
        uses: equisoft-actions/yarn-jest@v1

  compile:
    name: Compile
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup asdf-vm
        uses: equisoft-actions/with-asdf-vm@v2
      - name: Install NPM dependencies
        uses: equisoft-actions/yarn-install@v1
      - name: Compile
        run: |
          yarn type-check
          yarn package

      - name: Upload dist/
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: build/dist
          retention-days: 1

  eslint-annotations:
    name: Create ESLint annotations
    runs-on: ubuntu-latest
    needs:
      - eslint
      - compile
    if: ${{ failure() && needs.compile.result == 'success' && needs.eslint.result == 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download eslint results
        uses: actions/download-artifact@v3
        with:
          name: eslint.sarif
          path: build/eslint/
      - name: Download new dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: build/dist

      - name: Overwrite dist/ with the current build
        run: |
          cp -fr build/dist .

      - name: Create annotations
        uses: ./
        with:
          level: warning
          sarif-path: build/eslint/report.sarif
          title: ESLint results
